In [3]:
!pip install tensorflow


  Using cached tensorflow-2.19.0-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
  Using cached absl_py-2.2.2-py3-none-any.whl.metadata (2.6 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached grpcio-1.71.0-cp312-cp312-win_amd64.whl.metadata (4.0 kB)
  Using cached tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
  Using cached keras-3.9.2-py3-none-any.whl.metadata (6.1 kB)
  Using cached ml_dtypes-0.5.1-cp312-cp312-win_amd64.whl.metadata (22 kB)
  Using cached namex-0.0.9-py3-none-any.whl.metadata (322 bytes)
  Using cached optree-0.15.0-cp312-cp312-win_amd64.whl.metadata (49 kB)
  Using cached tenso

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Sri Lakshmi Prasanna\\anaconda3\\Lib\\site-packages\\clang\\native\\libclang.dll'
Consider using the `--user` option or check the permissions.




   --------------- ---------------------- 149.4/376.0 MB 285.0 kB/s eta 0:13:15
   --------------- ---------------------- 149.4/376.0 MB 285.0 kB/s eta 0:13:15
   --------------- ---------------------- 149.7/376.0 MB 248.0 kB/s eta 0:15:13
   --------------- ---------------------- 149.7/376.0 MB 248.0 kB/s eta 0:15:13
   --------------- ---------------------- 149.7/376.0 MB 248.0 kB/s eta 0:15:13
   --------------- ---------------------- 149.7/376.0 MB 248.0 kB/s eta 0:15:13
   --------------- ---------------------- 149.7/376.0 MB 248.0 kB/s eta 0:15:13
   --------------- ---------------------- 149.7/376.0 MB 248.0 kB/s eta 0:15:13
   --------------- ---------------------- 149.7/376.0 MB 248.0 kB/s eta 0:15:13
   --------------- ---------------------- 149.7/376.0 MB 248.0 kB/s eta 0:15:13
   --------------- ---------------------- 149.7/376.0 MB 248.0 kB/s eta 0:15:13
   --------------- ---------------------- 149.7/376.0 MB 248.0 kB/s eta 0:15:13
   --------------- --------------------

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
voc_size=10000

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8668, 2081, 1008, 5068], [8668, 2081, 1008, 7390], [8668, 3430, 1008, 3400], [6740, 7989, 6311, 7752, 9362], [6740, 7989, 6311, 7752, 2995], [9918, 8668, 6775, 1008, 3553], [9310, 7512, 7831, 7752]]


In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:

import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8668 2081 1008 5068]
 [   0    0    0    0 8668 2081 1008 7390]
 [   0    0    0    0 8668 3430 1008 3400]
 [   0    0    0 6740 7989 6311 7752 9362]
 [   0    0    0 6740 7989 6311 7752 2995]
 [   0    0    0 9918 8668 6775 1008 3553]
 [   0    0    0    0 9310 7512 7831 7752]]


In [12]:

dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Sri Lakshmi Prasanna\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step
[[[ 0.01826615 -0.04007738  0.01014692  0.02263261  0.00847936
    0.0265981  -0.00222305 -0.04154519  0.03969819  0.0418235 ]
  [ 0.01826615 -0.04007738  0.01014692  0.02263261  0.00847936
    0.0265981  -0.00222305 -0.04154519  0.03969819  0.0418235 ]
  [ 0.01826615 -0.04007738  0.01014692  0.02263261  0.00847936
    0.0265981  -0.00222305 -0.04154519  0.03969819  0.0418235 ]
  [ 0.01826615 -0.04007738  0.01014692  0.02263261  0.00847936
    0.0265981  -0.00222305 -0.04154519  0.03969819  0.0418235 ]
  [ 0.02050417  0.00844024 -0.03885365 -0.03745342  0.04113796
   -0.04773108  0.03024068  0.00366496 -0.01203147 -0.02089167]
  [-0.04566192  0.04149364  0.0210182  -0.03460091  0.02765217
    0.0328132   0.04696867 -0.01101404 -0.03544541 -0.04665413]
  [-0.02330463 -0.01793656  0.03269788  0.00483977  0.04604815
    0.03903979 -0.00745295  0.03952426 -0.0454382   0.03434605]
  [ 0.04306268 -0.00623804 -0.02846252 -0.01763066  0.01479275
    0.036

In [16]:

embedded_docs[0]

array([   0,    0,    0,    0, 8668, 2081, 1008, 5068])

In [17]:

print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[[ 0.01826615 -0.04007738  0.01014692  0.02263261  0.00847936  0.0265981
  -0.00222305 -0.04154519  0.03969819  0.0418235 ]
 [ 0.01826615 -0.04007738  0.01014692  0.02263261  0.00847936  0.0265981
  -0.00222305 -0.04154519  0.03969819  0.0418235 ]
 [ 0.01826615 -0.04007738  0.01014692  0.02263261  0.00847936  0.0265981
  -0.00222305 -0.04154519  0.03969819  0.0418235 ]
 [ 0.01826615 -0.04007738  0.01014692  0.02263261  0.00847936  0.0265981
  -0.00222305 -0.04154519  0.03969819  0.0418235 ]
 [ 0.02050417  0.00844024 -0.03885365 -0.03745342  0.04113796 -0.04773108
   0.03024068  0.00366496 -0.01203147 -0.02089167]
 [-0.04566192  0.04149364  0.0210182  -0.03460091  0.02765217  0.0328132
   0.04696867 -0.01101404 -0.03544541 -0.04665413]
 [-0.02330463 -0.01793656  0.03269788  0.00483977  0.04604815  0.03903979
  -0.00745295  0.03952426 -0.0454382   0.03434605]
 [ 0.04306268 -0.00623804 -0.02846252 -0.01763066  0.01479275  0.03632723
  -0.03760084  0.0